### ISSUE TITLE
Enigma Crash on certain server/s - suspected Issue with names coming from XC

### ISSUE THREAD

**Issue by LandRocket** [kiddac/Jedi_Maker_Xtream#9]
10:25:31.5606 Traceback (most recent call last):
10:25:31.5607   File "/usr/lib/enigma2/python/Plugins/Extensions/JediMakerXtream/buildbouquet.py", line 193, in buildBouquets
10:25:31.5614     self.process_category()
10:25:31.5615   File "/usr/lib/enigma2/python/Plugins/Extensions/JediMakerXtream/buildbouquet.py", line 232, in process_category
10:25:31.5619     self.buildBouquets()
10:25:31.5620   File "/usr/lib/enigma2/python/Plugins/Extensions/JediMakerXtream/buildbouquet.py", line 193, in buildBouquets
10:25:31.5624     self.process_category()
10:25:31.5624   File "/usr/lib/enigma2/python/Plugins/Extensions/JediMakerXtream/buildbouquet.py", line 218, in process_category
10:25:31.5628     self.epg_name_list = jfunc.process_category(category_name, category_type, category_id, self.domain, self.port, self.username, self.password, self.protocol, self.output, self.bouquet,
10:25:31.5629   File "/usr/lib/enigma2/python/Plugins/Extensions/JediMakerXtream/globalfunctions.py", line 504, in process_category
10:25:31.5647     streamvalues = sorted(streamvalues, key=lambda s: s['name'])
10:25:31.5648 TypeError: '<' not supported between instances of 'NoneType' and 'str'
10:25:31.5649 [ePyObject] (PyObject_CallObject(<bound method JediMakerXtream_BuildBouquets.buildBouquets of <class 'Plugins.Extensions.JediMakerXtream.buildbouquet.JediMakerXtream_BuildBouquets'>>,())

**Comment by hombergerkurde** [comment]
hello i have a dreambox one i have added an iptv line with jedi maker but i always get the error message unknown media type. I tried the same line on other recivers because it works without problems with jedimaker.
I also tried other lines that work on my drembox one with jedimaker.
i have the current version of jedimaker
